apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: eduonline
  labels:
    app: jaeger
    component: observability
spec:
  type: ClusterIP
  ports:
  - name: jgr-zipkin
    port: 6831
    targetPort: jgr-zipkin
    protocol: UDP
  - name: jgr-compact
    port: 6832
    targetPort: jgr-compact
    protocol: UDP
  - name: jgr-binary
    port: 6833
    targetPort: jgr-binary
    protocol: UDP
  - name: jaeger-query
    port: 16686
    targetPort: jaeger-query
    protocol: TCP
  - name: jaeger-admin
    port: 14269
    targetPort: jaeger-admin
    protocol: TCP
  - name: zipkin
    port: 9411
    targetPort: 9411
    protocol: TCP
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: eduonline
  labels:
    app: jaeger
    component: observability
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: jgr-zipkin
    port: 6831
    targetPort: jgr-zipkin
    protocol: UDP
  - name: jgr-compact
    port: 6832
    targetPort: jgr-compact
    protocol: UDP
  - name: jgr-binary
    port: 6833
    targetPort: jgr-binary
    protocol: UDP
  selector:
    app: jaeger
