apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: eduonline
  labels:
    app: grafana
    component: observability
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 3000
    targetPort: web
    protocol: TCP
  selector:
    app: grafana
