apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/eduonline/sqlserver
    type: DirectoryOrCreate
  claimRef:
    namespace: eduonline
    name: sqlserver-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
  namespace: eduonline
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  volumeName: sqlserver-pv
