apiVersion: v1
kind: Secret
metadata:
  name: eduonline-secrets
  namespace: eduonline
type: Opaque
stringData:
  SA_PASSWORD: P@ssw0rd2024!
  auth-connection-string: Server=sqlserver,1433;Database=EduOnlineDB;User Id=sa;Password=P@ssw0rd2024!;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True
  alunos-connection-string: Server=sqlserver,1433;Database=EduOnlineDB;User Id=sa;Password=P@ssw0rd2024!;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True
  conteudos-connection-string: Server=sqlserver,1433;Database=EduOnlineDB;User Id=sa;Password=P@ssw0rd2024!;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True
  pagamentos-connection-string: Server=sqlserver,1433;Database=EduOnlineDB;User Id=sa;Password=P@ssw0rd2024!;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True
  AppTokenSettings__Segredo: ChaveSuperSecretaParaJWT_2024_EduOnline_MinhaChaveDeve_TerMaisde32Caracteres!@#$%^&*
  AppSettings__Segredo: ChaveSuperSecretaParaJWT_2024_EduOnline_MinhaChaveDeve_TerMaisde32Caracteres!@#$%^&*
  RabbitMq__Password: EduOnlineRabbitMQ!2024
