apiVersion: v1
kind: Secret
metadata:
  name: eduonline-secrets
  namespace: eduonline
type: Opaque
stringData:
  SA_PASSWORD: "<set-via-external-secret-or-secure-bootstrap>"
  auth-connection-string: "Server=sqlserver,1433;Database=EduOnlineAuthDb;User Id=sa;Password=<set-via-external-secret-or-secure-bootstrap>;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True"
  alunos-connection-string: "Server=sqlserver,1433;Database=EduOnlineAlunosDb;User Id=sa;Password=<set-via-external-secret-or-secure-bootstrap>;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True"
  conteudos-connection-string: "Server=sqlserver,1433;Database=EduOnlineConteudosDb;User Id=sa;Password=<set-via-external-secret-or-secure-bootstrap>;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True"
  pagamentos-connection-string: "Server=sqlserver,1433;Database=EduOnlinePagamentosDb;User Id=sa;Password=<set-via-external-secret-or-secure-bootstrap>;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True"
  AppTokenSettings__Segredo: "<set-via-external-secret-or-secure-bootstrap>"
  AppSettings__Segredo: "<set-via-external-secret-or-secure-bootstrap>"
  RabbitMq__Password: "<set-via-external-secret-or-secure-bootstrap>"
