apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eduonline-secrets
  namespace: eduonline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: eduonline-vault-store
    kind: SecretStore
  target:
    name: eduonline-secrets
    creationPolicy: Owner
  data:
    - secretKey: auth-connection-string
      remoteRef:
        key: eduonline/auth-api/database
    - secretKey: alunos-connection-string
      remoteRef:
        key: eduonline/alunos-api/database
    - secretKey: conteudos-connection-string
      remoteRef:
        key: eduonline/conteudos-api/database
    - secretKey: pagamentos-connection-string
      remoteRef:
        key: eduonline/pagamentos-api/database
    - secretKey: jwt-secret
      remoteRef:
        key: eduonline/auth-api/jwt-secret
