apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: eduonline-vault-store
  namespace: eduonline
spec:
  provider:
    vault:
      server: http://vault:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eduonline-apps
          serviceAccountRef:
            name: vault
