apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eduonline

resources:
  - ../../

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/progressDeadlineSeconds
        value: 900
    target:
      kind: Deployment
      name: auth-api
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/progressDeadlineSeconds
        value: 900
    target:
      kind: Deployment
      name: conteudos-api
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/progressDeadlineSeconds
        value: 900
    target:
      kind: Deployment
      name: alunos-api
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/progressDeadlineSeconds
        value: 900
    target:
      kind: Deployment
      name: pagamentos-api
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/progressDeadlineSeconds
        value: 900
    target:
      kind: Deployment
      name: bff-api
