apiVersion: v1
kind: ServiceAccount
metadata:
  name: kibana
  namespace: eduonline
  labels:
    app: kibana
    component: observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kibana
  labels:
    app: kibana
    component: observability
rules:
- apiGroups: [""]
  resources:
  - services
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kibana
  labels:
    app: kibana
    component: observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kibana
subjects:
- kind: ServiceAccount
  name: kibana
  namespace: eduonline
