apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: eduonline
  labels:
    app: kibana
    component: observability
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 5601
    targetPort: web
    protocol: TCP
  selector:
    app: kibana
