apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eduonline-secrets
  namespace: eduonline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-eduonline
    kind: SecretStore
  target:
    name: eduonline-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: SA_PASSWORD
      remoteRef:
        key: eduonline/db
        property: sa_password
    - secretKey: auth-connection-string
      remoteRef:
        key: eduonline/db
        property: auth_connection_string
    - secretKey: alunos-connection-string
      remoteRef:
        key: eduonline/db
        property: alunos_connection_string
    - secretKey: conteudos-connection-string
      remoteRef:
        key: eduonline/db
        property: conteudos_connection_string
    - secretKey: pagamentos-connection-string
      remoteRef:
        key: eduonline/db
        property: pagamentos_connection_string
    - secretKey: AppTokenSettings__Segredo
      remoteRef:
        key: eduonline/jwt
        property: app_token_secret
    - secretKey: AppSettings__Segredo
      remoteRef:
        key: eduonline/jwt
        property: app_settings_secret
    - secretKey: RabbitMq__Password
      remoteRef:
        key: eduonline/messaging
        property: rabbitmq_password
