apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-eduonline
  namespace: eduonline
spec:
  provider:
    vault:
      server: https://vault.eduonline.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eduonline-api
