apiVersion: v1
kind: ServiceAccount
metadata:
  name: eduonline-api
  namespace: eduonline
  labels:
    app.kubernetes.io/name: eduonline-api
    app.kubernetes.io/part-of: eduonline-platform
automountServiceAccountToken: false
