apiVersion: v1
kind: Service
metadata:
  name: pagamentos-api
  namespace: eduonline
spec:
  type: ClusterIP
  selector:
    app: pagamentos-api
  ports:
    - name: http
      port: 5003
      targetPort: 5003
