apiVersion: v1
kind: Service
metadata:
  name: status-api
  namespace: eduonline
spec:
  type: ClusterIP
  selector:
    app: status-api
  ports:
    - name: http
      port: 5005
      targetPort: 5005
