apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: eduonline
  labels:
    app: vault
    component: security
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8200
    targetPort: http
    protocol: TCP
  - name: cluster
    port: 8201
    targetPort: cluster
    protocol: TCP
  selector:
    app: vault
