name: Build .NET e Rodar Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar o SDK do .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restaurar dependências e Build da Solução
      run: dotnet build EduOnline.slnx --configuration Release

  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Buildar e Subir o Docker Compose
      run: |
        docker compose build
        docker compose up -d
